#
# Copyright (C) 2016 Marvell International Ltd.
#
# SPDX-License-Identifier:	GPL-2.0
# https://spdx.org/licenses


obj-$(CONFIG_CMD_NETTEST) += cmd_nettest.o mactest.o io.o mac.o ncsi.o phy.o phygpio.o stduboot.o
